### ISSUE TITLE
3.0 compatibility

### ISSUE THREAD

**Issue by nirvn** [havochvatten/ImageServerConnector-QGIS-Plugin#5]
Is there any plan to make the plugin compatible with QGIS 3.X? QGIS 2.18 LTS (and therefore the whole QGIS 2.x branch) will reach its end of life on February 22, I hope this useful plugin will keep up :smile:

**Comment by antmyrhav** [comment]
Hello! It is unfortunate that we developed the plugin for the dying QGIS 2, there are plans to upgrade to version 3 in the coming months if we can get the time to do it. Happy to see that you found use for the plugin.

**Comment by KazzaS** [comment]
We can only have version 3 QGIS installations in our organisation, and we'd to use the upgrade too for our Planet and other satellite imagery data image services from the AWS cloud :-)!

**Comment by antmyrhav** [comment]
> We can only have version 3 QGIS installations in our organisation, and we'd to use the upgrade too for our Planet and other satellite imagery data image services from the AWS cloud :-)!

Today is the official release for 2.0.0 of this plugin that has QGIS 3 support. It is somewhat unstable and many servers haven't been tested, but it should work in some scenarios anyway. Would be happy if any undocumented issues are reported on here. :) 

It will be uploaded to the qgis repo soon, in the meanwhile you can find it under releases on here, be sure to get the final version.

**Comment by KazzaS** [comment]
Great thanks very much, Anton. It installed fine!  Once our authentication account is set-up I'll test it.

**Comment by KazzaS** [comment]
Good morning Anton,

Thank you very for releasing the version 2.0. It installed fine ☺.  I’m just waiting for my account to be a built-in Portal account and should be able to see the authenticated image service.

Kind regards, Karin

**Comment by nirvn** [comment]
@antmyrhav , FYI, the plugin fails to load here with the following error:

```
ImportError: cannot import name '_imaging' from 'ImageServerConnector.PIL' (/home/webmaster/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/PIL/__init__.py) 
Traceback (most recent call last):
  File "/home/webmaster/apps/share/qgis/python/qgis/utils.py", line 332, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/webmaster/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/__init__.py", line 12, in classFactory
    from .arcgiscon_plugin import ArcGisConnector
  File "/home/webmaster/apps/share/qgis/python/qgis/utils.py", line 714, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/webmaster/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/arcgiscon_plugin.py", line 17, in 
    from .layer_dialog_controller import LayerDialogController
  File "/home/webmaster/apps/share/qgis/python/qgis/utils.py", line 714, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/webmaster/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/layer_dialog_controller.py", line 13, in 
    from .PIL import Image
  File "/home/webmaster/apps/share/qgis/python/qgis/utils.py", line 714, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/webmaster/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/PIL/Image.py", line 94, in 
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'ImageServerConnector.PIL' (/home/webmaster/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/PIL/__init__.py)


Python version: 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0] 
QGIS version: 3.7.0-Master Master, 764aed89dc 
```

**Comment by antmyrhav** [comment]
Seems to work fine for me installing both from the github releases and qgis plugin repository, did you download the zip from the releases page or just a zip of the source code?

**Comment by nirvn** [comment]
@antmyrhav , tried through the plugin manager on my Ubuntu 19.04 machine.

**Comment by antmyrhav** [comment]
Good point, I am new to using libraries in python, I know what the cause might be and I will fix it asap, thanks for bringing it to my attention.

(Seems that copying site-packages folders for use is a bad idea for different platforms, will delete PIL since it is not really used much)

**Comment by antmyrhav** [comment]
@nirvn are you able to test it again? Uploaded 2.0.1 to the repo. I don't have access to any linux machine atm

**Comment by nirvn** [comment]
@antmyrhav , I'm off computers until the 15th enjoying the Buddhist's new year. I'll test ASAP.

Btw, the reloadData() fix will become public in the next wave of point release on the 19th, you'll be able to get rid of your hack then. 🎉

**Comment by KazzaS** [comment]
Hi Anton,

I'm getting the error:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: …s/ImageServer?f=json (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')) 
Traceback (most recent call last):
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\connection.py", line 314, in connect
    conn = self._new_conn()
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: …/ImageServer?f=json (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/…/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImageServerConnector\arcgiscon_controller.py", line 96, in _onUrlEdit
    self._initConnection()
  File "C:/Users/…/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImageServerConnector\arcgiscon_controller.py", line 102, in _initConnection
    self._connection = Connection.createAndConfigureConnection(url, "")
  File "C:/Users/…/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImageServerConnector\arcgiscon_model.py", line 492, in createAndConfigureConnection
    connection.configure(validator)
  File "C:/Users/…/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImageServerConnector\arcgiscon_model.py", line 500, in configure
    response = self.connect(query)
  File "C:/Users/…/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImageServerConnector\arcgiscon_model.py", line 575, in connect
    request = requests.post(self.basicUrl + query.getUrlAddon(), params=query.getParams(), auth=self.auth, timeout=180)
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\QGIS 3.6\apps\Python37\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: …?f=json (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by nirvn** [comment]
@antmyrhav , 2.0.1 loads fine on my machine, thanks.
