### ISSUE TITLE
Load error "ModuleNotFoundError: No module named 'future'"

### ISSUE THREAD

**Issue by secretmango** [havochvatten/ImageServerConnector-QGIS-Plugin#9]
```
Couldn't load plugin 'ImageServerConnector' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/__init__.py", line 12, in classFactory
    from .arcgiscon_plugin import ArcGisConnector
  File "/usr/lib64/python3.12/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/arcgiscon_plugin.py", line 12, in 
    from .arcgiscon_service import NotificationHandler, EsriUpdateService,\
  File "/usr/lib64/python3.12/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ImageServerConnector/arcgiscon_service.py", line 9, in 
    from future import standard_library
  File "/usr/lib64/python3.12/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'future'


Python version: 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] 
QGIS version: 3.32.3-Lima Lima, exported 
```

Using the Fedora39 version with python3-qgis and qgis 3.32

EDIT
running `pip install future` solved this, so I guess its just a dependency problem

**Comment by secretmango** [comment]
can this be solved on your side?
